# Generated by Django 5.2.5 on 2025-10-30 04:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('tabla', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario', models.IntegerField()),
            ],
        ),
    ]
