# Generated by Django 5.2.5 on 2025-11-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSocioeconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('dpi', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('ocupacion_padre', models.CharField(max_length=100)),
                ('ingreso_padre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ocupacion_madre', models.CharField(max_length=100)),
                ('ingreso_madre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_personas_hogar', models.IntegerField()),
                ('motivo_solicitud', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'solicitudes_socioeconomicas',
            },
        ),
    ]
