# Generated by Django 5.2.5 on 2025-11-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socioeconomico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socioeconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('dpi', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('ocupacion_padre', models.CharField(max_length=255)),
                ('ingreso_padre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ocupacion_madre', models.CharField(max_length=255)),
                ('ingreso_madre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_personas_hogar', models.IntegerField()),
                ('motivo_beca', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='SolicitudSocioeconomica',
        ),
    ]
